---
title: "Downloading raw SeaAroundUs data"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ohiprep/src/templates/ohi_hdr.html'
pdf_document:
  toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F,warning=F)

library(seaaroundus)
library(raster)
library(data.table)
library(tidyverse)

source('~/github/ohiprep/src/R/common.R')


```

# Get all cell values
```{r}

# Get cell id numbers from data we have matching saup cells to ohi regions
cells_raw <- read.csv(file.path(dir_M, "git-annex/globalprep/fis/v2015/raw/saup_rasters_to_ohi_rgns.csv"))%>%
              rename(CellID=saup_cell_id)

## check that I got these right!  - these are right (JA - 8/8/26)
eez_fao_cats <- c("eez", "eez-ccamlr", "eez-ccamlr, land-ccamlr", "eez-disputed",
                  "eez-disputed, fao", "eez-disputed, land-disputed", "eez-disputed, land, land-disputed", "eez, eez-ccamlr",
                  "eez, eez-disputed", "eez, eez-disputed, fao", "eez, eez-disputed, land", "eez, eez-disputed, land-disputed",
                  "eez, eez-disputed, land, land-disputed", "eez, fao", "eez, land", "eez, land, land-noeez", "fao")  

## get a list of cells that have eez or fao categories:
## used later to determine whether cells with OHI regions but no FAO region are an issue:
cells_water <- cells_raw %>%
                group_by(CellID) %>%
                mutate(cell_rgns = paste(sort(unique(rgn_typ)), collapse=", ")) %>%
                arrange(CellID)%>%
                filter(CellID, cell_rgns %in% eez_fao_cats)

```
   
# Get data for each year  

```{r}

saup_cells <- unique(cells_water$CellID)

batches <- seq(1, length(saup_cells), 200)

yr <- 2014
out <- list()

pb <- utils::txtProgressBar(min = 0, max = length(batches), initial = 0, style = 3)
for (i in seq_along(batches)){
  utils::setTxtProgressBar(pb, i)
  print(i)
  start <- batches[i]
  end <- start + 199
  
  batchn <- saup_cells[start:end]
  
  out[[i]] <- getcelldata(year=yr, batchn)
  Sys.sleep(1)
}
close(pb)

df <- bind_rows(out)
  saveRDS(df, paste0(file.path(dir_M),"/git-annex/globalprep/_raw_data/SAUP/d2017/annual_data/saup_data_",yr,".rds"))

```
   
   
   
   