####################################################################
## Fisheries (FIS) calculation (Part 1):
## Data preparation (b/bmsy data generated by cmsy_ohi.R)
####################################################################
source('~/ohiprep/src/R/common.R')

library(reshape2)
library(stringr)

data_files <- "Global/GL-AQ-FIS_v2013"

#---------------------------------------------------------
## CMSY data: 3 additional taxa (these have c/cmsy data) ----
#---------------------------------------------------------
cmsy <- read.csv("raw/Ant_C_Cmsy .csv")
cmsy <- cmsy %.%
  select(taxon_name=ScientificName, fao_id=area, year=season.year, C_msy_assmt) %.%
  group_by(taxon_name, fao_id, year) %.%
  summarise(C_msy_assmt = mean(C_msy_assmt, na.rm=TRUE))  #some multiple scores that need to be averaged

cmsy <- data.frame(cmsy)

cmsy <- cmsy %.%
  mutate(fao_id = as.character(fao_id)) %.%
  mutate(fao_id = gsub("\\.", "", fao_id)) %.%
  mutate(fao_id = gsub("a", "1", fao_id)) %.%
  mutate(fao_id = as.numeric(gsub("b", "2", fao_id)))

## appears the best route is to use the 2011 data for both 2011 and 2012,
## (rather than linear model to predict 2012) 

## adding in 2012 ccmsy estimates based on 2011 data for taxon/regions
new <- data.frame(taxon_name="Champsocephalus gunnari", fao_id=c(483, 5852), year=2012, C_msy_assmt=c(0.18, 0.13))
cmsy <- rbind(cmsy, new)


write.csv(cmsy, file.path(data_files, "data\\fnk_fis_ccmsy.csv"), row.names=FALSE)

#---------------------------------------------------------
## Catch data ----
#---------------------------------------------------------

catchData <- read.csv("Global/GL-AQ-FIS_v2013/raw/CCAMLR_w_update_v2.csv") # N=3236

catchData[catchData$ASD==481 & catchData$ScientificName == "Champsocephalus gunnari", ]
table(catchData$ASD)
table(catchData$ASD2)
# organize/clean data
catchData2  <- catchData %>%
  filter(!(ASD %in% c(41, 48, 58, 88, 584, 585, 4132, 5843, 5844))) %>% #N=3059
  mutate(ASD = gsub("a", "1", ASD)) %>%
  mutate(ASD = as.numeric(gsub("b", "2", ASD)),
        fao_saup_id = paste(ASD, 0, sep="_"), 
        taxon_name_key = paste(ScientificName, Tax_Lev, sep="_")) %>%
  select(fao_saup_id, taxon_name_key, year=season.year, catch=corr.Catch2) %>%
  arrange(fao_saup_id, taxon_name_key, year)
catchData2[catchData2$fao_saup_id=='481_0' & catchData2$taxon_name_key == "Champsocephalus gunnari_6", ]  

# Calculate mean catch over all years per taxon and saup_id/fao_id
MeanCatch <- catchData %.%
 group_by(fao_saup_id, taxon_name_key) %>% 
  filter(year>=1980) %>%
 summarize(mean_catch=mean(catch, na.rm=TRUE))
MeanCatch[MeanCatch$fao_saup_id=='481_0' & MeanCatch$taxon_name_key == "Champsocephalus gunnari_6", ]

country.level.data <- merge(catchData, MeanCatch, by=c("fao_saup_id", "taxon_name_key"))

country.level.data[country.level.data$fao_saup_id=='481_0' & country.level.data$taxon_name_key == "Champsocephalus gunnari_6", ]

country.level.data <- country.level.data %>%
  filter(mean_catch != 0) %>% #cut catch with zero values
  filter(year>2005) %>%
  arrange(fao_saup_id, taxon_name_key, year)

write.csv(country.level.data, file.path(data_files, "data/cnk_fis_meancatch.csv"), row.names=FALSE)

