---
title: "Playing with datalimited models on SAUP data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
  toc: true
number_sections: true
theme: cerulean
highlight: haddock
includes: 
  in_header: '~/github/ohibc/src/templates/ohibc_hdr1.html'
pdf_document:
  toc: true
---

```{r setup, include=FALSE}

library(datalimited) #has the 4 catch only models
library(dplyr)
library(doParallel)
registerDoParallel(cores = 8)

source('~/github/ohiprep/src/R/common.R')

```


```{r catch_data}

catch <- read.csv('../int/catch_pre_bbmsy.csv')

```

# Catch-MSY

```{r cmsy}

if (!file.exists(file.path(dir_M,"git-annex/globalprep/fis/v2016/int/cmsy-fits.rds"))) {
  
cmsy_fits <- plyr::dlply(catch, c("stock_id", "common"), function(x) {
  
    #make sure the data is ordered from 1950 to 2010
    x <- arrange(x,year)
    out <- cmsy(ct = x$tons, yr = x$year,  start_r = resilience(x$Resilience[1]), 
      reps = 2e4)
    out$year <- x$year
    out
  }, .parallel = TRUE)
saveRDS(cmsy_fits, file = file.path(dir_M,"git-annex/globalprep/fis/v2016/int/cmsy-fits.rds"))
} else {
  cmsy_fits <- readRDS(file.path(dir_M,"git-annex/globalprep/fis/v2016/int/cmsy-fits.rds"))
}

fake_data <- data.frame(bbmsy_q2.5 = NA, bbmsy_q25 = NA, bbmsy_q50 = NA, 
  bbmsy_q75 = NA, bbmsy_q97.5 = NA)

cmsy_bbmsy <- plyr::ldply(cmsy_fits, function(x) {
  bbmsy_cmsy <- x$biomass[, -1] / x$bmsy
  bbmsy_out <- tryCatch({
    bbmsy_out <- summarize_bbmsy(bbmsy_cmsy)
    bbmsy_out$year <- x$year
    bbmsy_out}, error = function(e) fake_data)
})
cmsy_bbmsy$model <- "CMSY"

write.csv(cmsy_bbmsy,file='int/cmsy_bbmsy.csv')

```

Explore why there are some NAs (I think non convergance)

```{r nas}

nas <- cmsy_bbmsy%>%
  group_by(stock_id)%>%
  summarize(m = mean(bbmsy_mean))%>%
  filter(is.na(m))

nrow(nas)

```


### Running cmsy with a uniform prior

```{r cmsy_uni_prior}

if (!file.exists(file.path(dir_M,"git-annex/globalprep/fis/v2016/int/cmsy-fits-uni-prior.rds"))) {
cmsy_fits_uni <- plyr::dlply(catch, c("stock_id", "common"), function(x) {
  
  #make sure the data is ordered from 1950 to 2010
     x <- arrange(x,year)
     
    out <- cmsy(x$tons, yr = x$year,  start_r = resilience(x$Resilience[1]), 
      reps = 2e4, finalbio = c(0.01, 0.7))
    out$year <- x$year
    out
  }, .parallel = TRUE)
saveRDS(cmsy_fits_uni, file = file.path(dir_M,"git-annex/globalprep/fis/v2016/int/cmsy-fits-uni-prior.rds"))
} else {
  cmsy_fits_uni <- readRDS(file.path(dir_M,"git-annex/globalprep/fis/v2016/int/cmsy-fits-uni-prior.rds"))
}

fake_data <- data.frame(bbmsy_q2.5 = NA, bbmsy_q25 = NA, bbmsy_q50 = NA, 
  bbmsy_q75 = NA, bbmsy_q97.5 = NA)

cmsy_bbmsy_uni <- plyr::ldply(cmsy_fits_uni, function(x) {
  bbmsy_cmsy <- x$biomass[, -1] / x$bmsy
  bbmsy_out <- tryCatch({
    bbmsy_out <- summarize_bbmsy(bbmsy_cmsy)
    bbmsy_out$year <- x$year
    bbmsy_out}, error = function(e) fake_data)
})
cmsy_bbmsy_uni$model <- "CMSY_uniform"

write.csv(cmsy_bbmsy_uni,file="int/cmsy_bbmsy_uni_prior.csv")

```


# COMSIR

The output of running COMSIR created 9 individual dataframes. This is a result of debugging. I kept getting a "missing value where TRUE/FALSE needed" error but wasn't able to identify what species was causing this.

```{r fit-comsir}

all.stocks<-unique(catch$stock_id)
##
batch1.stocks<-all.stocks[1:317]
batch2.stocks<-all.stocks[318:635]
batch3.stocks<-all.stocks[636:700]
batch4.stocks<-all.stocks[701:800]
batch5.stocks<-all.stocks[801:1000]
batch6.stocks<-all.stocks[1001:1050]
batch7.stocks<-all.stocks[1051:1100]
batch8.stocks<-all.stocks[1101:1200]
batch9.stocks<-all.stocks[1201:1267]
##

#for loop
for (i in 1:9){
  
#subset the catch to match stocks in each of the 9 batches  
input<-subset(catch, stock_id%in%get(paste("batch",i,".stocks",sep="")))
  
#run the comsir model function on each stock_id within input
comsir_fits <- plyr::dlply(input, c("stock_id", "common"), function(x) {
    out <- comsir(ct = x$tons, yr = x$year,  start_r = resilience(x$Resilience[1]), 
      nsim = 2e6, n_posterior = 5e3)
  }, .parallel = TRUE)

#save the data as an RDS
saveRDS(comsir_fits, file = paste0(file.path(dir_M),"/git-annex/globalprep/fis/v2016/int/comsir-fits_",i,".rds"))


fake_data <- data.frame(bbmsy_q2.5 = NA, bbmsy_q25 = NA, bbmsy_q50 = NA, 
  bbmsy_q75 = NA, bbmsy_q97.5 = NA)

#take the fits and create a dataframe with the bbmsy

comsir_bbmsy <- plyr::ldply(comsir_fits, function(x) {
  tryCatch({
    out <- reshape2::dcast(x$quantities, sample_id ~ yr, value.var = "bbmsy")[,-1]
    out <- summarize_bbmsy(out)
    out$year <- unique(x$quantities$yr)
    out}, 
    error = function(e) fake_data)
})

  #add model column defining COM-SIR
  comsir_bbmsy$model <- "COM-SIR"
  
  #save as csv
  write.csv(comsir_bbmsy,file=paste0("int/comsir/comsir-bbmsy_",i,".csv"))

} 

```


Combine the 9 .csvs into one dataset.
```{r combine_COMSIR}

files <- list.files('int/comsir',full.names=T)

tables <- lapply(files, read.csv)
comsir_all <- do.call(rbind, tables)

write.csv(comsir_all,file='int/comsir_bbmsy.csv')

```






