####################################################################
## Fisheries (FIS) calculation (Part 1):
## Data preparation (b/bmsy data generated by cmsy_ohi.R)
####################################################################
source('~/ohiprep/src/R/common.R')

library(reshape2)
library(stringr)

data_files <- "Antarctica/AQ_FIS_v2013"

#---------------------------------------------------------
## CMSY data: 3 additional taxa (these have c/cmsy data) ----
#---------------------------------------------------------
cmsy <- read.csv(file.path(data_files, "raw/Ant_C_Cmsy .csv"))
cmsy <- cmsy %.%
  select(taxon_name=ScientificName, fao_id=area, year=season.year, C_msy_assmt) %.%
  group_by(taxon_name, fao_id, year) %.%
  summarise(C_msy_assmt = mean(C_msy_assmt, na.rm=TRUE))  #some multiple scores that need to be averaged

cmsy <- data.frame(cmsy)

cmsy <- cmsy %.%
  mutate(fao_id = as.character(fao_id)) %.%
  mutate(fao_id = gsub("\\.", "", fao_id)) %.%
  mutate(fao_id = gsub("a", "1", fao_id)) %.%
  mutate(fao_id = as.numeric(gsub("b", "2", fao_id)))

## appears the best route is to use the 2011 data for both 2011 and 2012,
## (rather than linear model to predict 2012) 

## adding in 2012 ccmsy estimates based on 2011 data for taxon/regions
new <- data.frame(taxon_name="Champsocephalus gunnari", fao_id=c(483, 5852), year=2012, C_msy_assmt=c(0.18, 0.13))
cmsy <- rbind(cmsy, new)


write.csv(cmsy, file.path(data_files, "data/fnk_fis_ccmsy.csv"), row.names=FALSE)

#---------------------------------------------------------
## Mean catch data ----
#---------------------------------------------------------

catchData <- read.csv(file.path(data_files, "tmp/CCAMLR_ct_rgn_Aug29_2014.csv")) # N=3236

# organize/clean data
catchData  <- catchData %>%
  filter(!(ASD %in% c(41, 48, 58, 88, 584, 585, 4132, 5843, 5844))) %>% #N=3059 
  mutate(ASD = gsub("a", "1", ASD)) %>%
  mutate(ASD = as.numeric(gsub("b", "2", ASD)),
        fao_saup_id = paste(ASD, 0, sep="_"), 
        taxon_name_key = paste(ScientificName, TL, sep="_")) %>%
  select(fao_saup_id, taxon_name_key, year=yr, catch=ct) %>%
  arrange(fao_saup_id, taxon_name_key, year) %>%
  filter(year>=1980)


# Calculate mean catch over all years >=1980 per taxon and saup_id/fao_id
MeanCatch <- catchData %.%
 group_by(fao_saup_id, taxon_name_key) %>% 
 mutate(mean_catch=mean(catch, na.rm=TRUE)) %>%
  filter(mean_catch != 0) %>% #cut catch with zero values
  filter(year>2005) %>%
  arrange(fao_saup_id, taxon_name_key, year)

# # The following code adds the mean catch to years with no catch record after catch is documented for a region.
# # This changes the results for some regions pretty dramatically.  We will want to explore this in future versions 
# # of the data.
# MeanCatch_zero <- catchData %>%
#          mutate(id=paste(taxon_name_key, fao_saup_id, sep="_")) 
# MeanCatch_minYear  <- MeanCatch_zero %>%
#         group_by(id) %>%
#          summarize(minYear=min(year))
# 
# MeanCatch_zero2 <- expand.grid(id=unique(MeanCatch_zero$id), year=1980:2012) %>%
#   mutate(fao_saup_id = paste(sapply(strsplit(as.character(id), "_"), function(x)x[3]), 0, sep="_"),
#          taxon_name_key = paste(sapply(strsplit(as.character(id), "_"), function(x)x[1]), 
#                                 sapply(strsplit(as.character(id), "_"), function(x)x[2]), sep="_"),
#          id=as.character(id)) %>%
#   left_join(MeanCatch_zero, by=c("id", "year", "fao_saup_id", "taxon_name_key")) %>%
#   left_join(MeanCatch_minYear) %>%
#   group_by(fao_saup_id, taxon_name_key) %>%
#   mutate(mean_catch=(mean(catch, na.rm=TRUE))) %>%
#   mutate(delete = ifelse(year<minYear, "yes", "no")) %>%
#   filter(delete=="no") %>%
#   select(fao_saup_id, taxon_name_key, year, catch, mean_catch) %>%
#   filter(mean_catch != 0) %>% #cut catch with zero values
#   filter(year>2005) %>%
#   arrange(fao_saup_id, taxon_name_key, year)


  write.csv(MeanCatch, file.path(data_files, "data/cnk_fis_meancatch.csv"), row.names=FALSE)

