SPP: Species 2014 vs 2013 Report
========================================================

Duplicates detected for 2014. Checking if existed in outputs from 2013.

Versions:
* **2013**: _**2013.1**_ (as of Jul 1,  2013)
* **2014**: _**2013.2**_ (as of Apr 20, 2014)


```{r setup}
library(dplyr)
library(knitr)
options(knitr.table.format='markdown')

setwd('~/ohiprep') # specific to host, eg neptune

# directories
source('src/R/common.R')
# working dir in local github repo
nm = 'Global/NCEAS-SpeciesDiversity_v2014'
wd = file.path(getwd(), nm)
# data dir
dd    = file.path(dir_neptune_data, 'git-annex', nm)
dd.13 = file.path(dir_neptune_data, 'model/GL-NCEAS-SpeciesDiversity_v2013a')

# data
spp_iucn_all       = read.csv(file.path(dd   , 'cache', 'spp_iucn_all.csv'   ), na.strings='')
spp_iucn_marine    = read.csv(file.path(dd   , 'cache', 'spp_iucn_marine.csv'), na.strings='')
spp_iucn_all.13    = read.csv(file.path(dd.13, 'tmp'  , 'spp_iucn_all.csv'   ), na.strings='')
spp_iucn_marine.13 = read.csv(file.path(dd.13, 'tmp'  , 'spp_iucn_marine.csv'), na.strings='')
```

## Check for Duplicates

```{r sid dupes}
names(spp_iucn_all)
table(duplicated(spp_iucn_all$Red.List.Species.ID))

names(spp_iucn_all.13)
table(duplicated(spp_iucn_all.13$Red.List.Species.ID))

dim(spp_iucn_marine)
dim(spp_iucn_marine.13)
```

Ok, confirmed that use of `Primary` is new to IUCN 2014 data.

```{r ex_cat, results='asis', echo=FALSE}
d = spp_iucn_marine.13 %.%
          group_by(category) %.%
          summarize(freq_2013=n()) %.%
  merge(spp_iucn_marine %.%
          group_by(category) %.%
          summarise(freq_2014 = n()),
        by='category') %.%
  mutate(freq_dif = freq_2014 - freq_2013)
kable(d, row.names=F)
```